export const jokerNames: Record<string, string> = {
  j_joker: 'Joker',
  j_greedy_joker: 'Greedy Joker',
  j_lusty_joker: 'Lusty Joker',
  j_wrathful_joker: 'Wrathful Joker',
  j_gluttenous_joker: 'Gluttonous Joker',
  j_jolly: 'Jolly Joker',
  j_zany: 'Zany Joker',
  j_mad: 'Mad Joker',
  j_crazy: 'Crazy Joker',
  j_droll: 'Droll Joker',
  j_sly: 'Sly Joker',
  j_wily: 'Wily Joker',
  j_clever: 'Clever Joker',
  j_devious: 'Devious Joker',
  j_crafty: 'Crafty Joker',
  j_half: 'Half Joker',
  j_stencil: 'Joker Stencil',
  j_four_fingers: 'Four Fingers',
  j_mime: 'Mime',
  j_credit_card: 'Credit Card',
  j_ceremonial: 'Ceremonial Dagger',
  j_banner: 'Banner',
  j_mystic_summit: 'Mystic Summit',
  j_marble: 'Marble Joker',
  j_loyalty_card: 'Loyalty Card',
  j_8_ball: '8 Ball',
  j_misprint: 'Misprint',
  j_dusk: 'Dusk',
  j_raised_fist: 'Raised Fist',
  j_chaos: 'Chaos the Clown',
  j_fibonacci: 'Fibonacci',
  j_steel_joker: 'Steel Joker',
  j_scary_face: 'Scary Face',
  j_abstract: 'Abstract Joker',
  j_delayed_grat: 'Delayed Gratification',
  j_hack: 'Hack',
  j_pareidolia: 'Pareidolia',
  j_gros_michel: 'Gros Michel',
  j_even_steven: 'Even Steven',
  j_odd_todd: 'Odd Todd',
  j_scholar: 'Scholar',
  j_business: 'Business Card',
  j_supernova: 'Supernova',
  j_ride_the_bus: 'Ride the Bus',
  j_space: 'Space Joker',
  j_egg: 'Egg',
  j_burglar: 'Burglar',
  j_blackboard: 'Blackboard',
  j_runner: 'Runner',
  j_ice_cream: 'Ice Cream',
  j_dna: 'DNA',
  j_splash: 'Splash',
  j_blue_joker: 'Blue Joker',
  j_sixth_sense: 'Sixth Sense',
  j_constellation: 'Constellation',
  j_hiker: 'Hiker',
  j_faceless: 'Faceless Joker',
  j_green_joker: 'Green Joker',
  j_superposition: 'Superposition',
  j_todo_list: 'To Do List',
  j_cavendish: 'Cavendish',
  j_card_sharp: 'Card Sharp',
  j_red_card: 'Red Card',
  j_madness: 'Madness',
  j_square: 'Square Joker',
  j_seance: 'Séance',
  j_riff_raff: 'Riff-Raff',
  j_vampire: 'Vampire',
  j_shortcut: 'Shortcut',
  j_hologram: 'Hologram',
  j_vagabond: 'Vagabond',
  j_baron: 'Baron',
  j_cloud_9: 'Cloud 9',
  j_rocket: 'Rocket',
  j_obelisk: 'Obelisk',
  j_midas_mask: 'Midas Mask',
  j_luchador: 'Luchador',
  j_photograph: 'Photograph',
  j_gift: 'Gift Card',
  j_turtle_bean: 'Turtle Bean',
  j_erosion: 'Erosion',
  j_reserved_parking: 'Reserved Parking',
  j_mail: 'Mail-In Rebate',
  j_to_the_moon: 'To the Moon',
  j_hallucination: 'Hallucination',
  j_fortune_teller: 'Fortune Teller',
  j_juggler: 'Juggler',
  j_drunkard: 'Drunkard',
  j_stone: 'Stone Joker',
  j_golden: 'Golden Joker',
  j_lucky_cat: 'Lucky Cat',
  j_baseball: 'Baseball Card',
  j_bull: 'Bull',
  j_diet_cola: 'Diet Cola',
  j_trading: 'Trading Card',
  j_flash: 'Flash Card',
  j_popcorn: 'Popcorn',
  j_trousers: 'Spare Trousers',
  j_ancient: 'Ancient Joker',
  j_ramen: 'Ramen',
  j_walkie_talkie: 'Walkie Talkie',
  j_selzer: 'Seltzer',
  j_castle: 'Castle',
  j_smiley: 'Smiley Face',
  j_campfire: 'Campfire',
  j_ticket: 'Golden Ticket',
  j_mr_bones: 'Mr. Bones',
  j_acrobat: 'Acrobat',
  j_sock_and_buskin: 'Sock and Buskin',
  j_swashbuckler: 'Swashbuckler',
  j_troubadour: 'Troubadour',
  j_certificate: 'Certificate',
  j_smeared: 'Smeared Joker',
  j_throwback: 'Throwback',
  j_hanging_chad: 'Hanging Chad',
  j_rough_gem: 'Rough Gem',
  j_bloodstone: 'Bloodstone',
  j_arrowhead: 'Arrowhead',
  j_onyx_agate: 'Onyx Agate',
  j_glass: 'Glass Joker',
  j_ring_master: 'Showman',
  j_flower_pot: 'Flower Pot',
  j_blueprint: 'Blueprint',
  j_wee: 'Wee Joker',
  j_merry_andy: 'Merry Andy',
  j_oops: 'Oops! All 6s',
  j_idol: 'The Idol',
  j_seeing_double: 'Seeing Double',
  j_matador: 'Matador',
  j_hit_the_road: 'Hit the Road',
  j_duo: 'The Duo',
  j_trio: 'The Trio',
  j_family: 'The Family',
  j_order: 'The Order',
  j_tribe: 'The Tribe',
  j_stuntman: 'Stuntman',
  j_invisible: 'Invisible Joker',
  j_brainstorm: 'Brainstorm',
  j_satellite: 'Satellite',
  j_shoot_the_moon: 'Shoot the Moon',
  j_drivers_license: "Driver's License",
  j_cartomancer: 'Cartomancer',
  j_astronomer: 'Astronomer',
  j_burnt: 'Burnt Joker',
  j_bootstraps: 'Bootstraps',
  j_caino: 'Canio',
  j_triboulet: 'Triboulet',
  j_yorick: 'Yorick',
  j_chicot: 'Chicot',
  j_perkeo: 'Perkeo',
}

export const jokerSprites: Record<string, string> = {
  j_joker: '0 0',
  j_greedy_joker: '-600% -100%',
  j_lusty_joker: '-700% -100%',
  j_wrathful_joker: '-800% -100%',
  j_gluttenous_joker: '-900% -100%',
  j_jolly: '-200% -0%',
  j_zany: '-300% -0%',
  j_mad: '-400% -0%',
  j_crazy: '-500% -0%',
  j_droll: '-600% -0%',
  j_sly: '-0% -1400%',
  j_wily: '-100% -1400%',
  j_clever: '-200% -1400%',
  j_devious: '-300% -1400%',
  j_crafty: '-400% -1400%',
  j_half: '-700% -0%',
  j_stencil: '-200% -500%',
  j_four_fingers: '-600% -600%',
  j_mime: '-400% -100%',
  j_credit_card: '-500% -100%',
  j_ceremonial: '-500% -500%',
  j_banner: '-100% -200%',
  j_mystic_summit: '-200% -200%',
  j_marble: '-300% -200%',
  j_loyalty_card: '-400% -200%',
  j_8_ball: '-0% -500%',
  j_misprint: '-600% -200%',
  j_dusk: '-400% -700%',
  j_raised_fist: '-800% -200%',
  j_chaos: '-100% -0%',
  j_fibonacci: '-100% -500%',
  j_steel_joker: '-700% -200%',
  j_scary_face: '-200% -300%',
  j_abstract: '-300% -300%',
  j_delayed_grat: '-400% -300%',
  j_hack: '-500% -200%',
  j_pareidolia: '-600% -300%',
  j_gros_michel: '-700% -600%',
  j_even_steven: '-800% -300%',
  j_odd_todd: '-900% -300%',
  j_scholar: '-300% -600%',
  j_business: '-100% -400%',
  j_supernova: '-200% -400%',
  j_ride_the_bus: '-100% -600%',
  j_space: '-300% -500%',
  j_egg: '-0% -1000%',
  j_burglar: '-100% -1000%',
  j_blackboard: '-200% -1000%',
  j_runner: '-300% -1000%',
  j_ice_cream: '-400% -1000%',
  j_dna: '-500% -1000%',
  j_splash: '-600% -1000%',
  j_blue_joker: '-700% -1000%',
  j_sixth_sense: '-800% -1000%',
  j_constellation: '-900% -1000%',
  j_hiker: '-0% -1100%',
  j_faceless: '-100% -1100%',
  j_green_joker: '-200% -1100%',
  j_superposition: '-300% -1100%',
  j_todo_list: '-400% -1100%',
  j_cavendish: '-500% -1100%',
  j_card_sharp: '-600% -1100%',
  j_red_card: '-700% -1100%',
  j_madness: '-800% -1100%',
  j_square: '-900% -1100%',
  j_seance: '-0% -1200%',
  j_riff_raff: '-100% -1200%',
  j_vampire: '-200% -1200%',
  j_shortcut: '-300% -1200%',
  j_hologram: '-400% -1200%',
  j_vagabond: '-500% -1200%',
  j_baron: '-600% -1200%',
  j_cloud_9: '-700% -1200%',
  j_rocket: '-800% -1200%',
  j_obelisk: '-900% -1200%',
  j_midas_mask: '-0% -1300%',
  j_luchador: '-100% -1300%',
  j_photograph: '-200% -1300%',
  j_gift: '-300% -1300%',
  j_turtle_bean: '-400% -1300%',
  j_erosion: '-500% -1300%',
  j_reserved_parking: '-600% -1300%',
  j_mail: '-700% -1300%',
  j_to_the_moon: '-800% -1300%',
  j_hallucination: '-900% -1300%',
  j_fortune_teller: '-700% -500%',
  j_juggler: '-0% -100%',
  j_drunkard: '-100% -100%',
  j_stone: '-900% -0%',
  j_golden: '-900% -200%',
  j_lucky_cat: '-500% -1400%',
  j_baseball: '-600% -1400%',
  j_bull: '-700% -1400%',
  j_diet_cola: '-800% -1400%',
  j_trading: '-900% -1400%',
  j_flash: '-0% -1500%',
  j_popcorn: '-100% -1500%',
  j_trousers: '-400% -1500%',
  j_ancient: '-700% -1500%',
  j_ramen: '-200% -1500%',
  j_walkie_talkie: '-800% -1500%',
  j_selzer: '-300% -1500%',
  j_castle: '-900% -1500%',
  j_smiley: '-600% -1500%',
  j_campfire: '-500% -1500%',
  j_ticket: '-500% -300%',
  j_mr_bones: '-300% -400%',
  j_acrobat: '-200% -100%',
  j_sock_and_buskin: '-300% -100%',
  j_swashbuckler: '-900% -500%',
  j_troubadour: '-0% -200%',
  j_certificate: '-800% -800%',
  j_smeared: '-400% -600%',
  j_throwback: '-500% -700%',
  j_hanging_chad: '-900% -600%',
  j_rough_gem: '-900% -700%',
  j_bloodstone: '-0% -800%',
  j_arrowhead: '-100% -800%',
  j_onyx_agate: '-200% -800%',
  j_glass: '-100% -300%',
  j_ring_master: '-600% -500%',
  j_flower_pot: '-0% -600%',
  j_blueprint: '-0% -300%',
  j_wee: '-0% -0%',
  j_merry_andy: '-800% -0%',
  j_oops: '-500% -600%',
  j_idol: '-600% -700%',
  j_seeing_double: '-400% -400%',
  j_matador: '-400% -500%',
  j_hit_the_road: '-800% -500%',
  j_duo: '-500% -400%',
  j_trio: '-600% -400%',
  j_family: '-700% -400%',
  j_order: '-800% -400%',
  j_tribe: '-900% -400%',
  j_stuntman: '-800% -600%',
  j_invisible: '-100% -700%',
  j_brainstorm: '-700% -700%',
  j_satellite: '-800% -700%',
  j_shoot_the_moon: '-200% -600%',
  j_drivers_license: '-0% -700%',
  j_cartomancer: '-700% -300%',
  j_astronomer: '-200% -700%',
  j_burnt: '-300% -700%',
  j_bootstraps: '-900% -800%',
  j_caino: '-300% -800%',
  j_triboulet: '-400% -800%',
  j_yorick: '-500% -800%',
  j_chicot: '-600% -800%',
  j_perkeo: '-700% -800%',
  undiscovered: '-900% -900%',
}

export const jokerExtraSprites: Record<string, string> = {
  j_hologram: '-200% -900%',
  j_caino: '-300% -900%',
  j_triboulet: '-400% -900%',
  j_yorick: '-500% -900%',
  j_chicot: '-600% -900%',
  j_perkeo: '-700% -900%',
  undiscovered: '-500% -300%',
}

export const jokerRarity: Record<string, string> = {
  j_joker: 'Common',
  j_greedy_joker: 'Common',
  j_lusty_joker: 'Common',
  j_wrathful_joker: 'Common',
  j_gluttenous_joker: 'Common',
  j_jolly: 'Common',
  j_zany: 'Common',
  j_mad: 'Common',
  j_crazy: 'Common',
  j_droll: 'Common',
  j_sly: 'Common',
  j_wily: 'Common',
  j_clever: 'Common',
  j_devious: 'Common',
  j_crafty: 'Common',
  j_half: 'Common',
  j_stencil: 'Uncommon',
  j_four_fingers: 'Uncommon',
  j_mime: 'Uncommon',
  j_credit_card: 'Common',
  j_ceremonial: 'Uncommon',
  j_banner: 'Common',
  j_mystic_summit: 'Common',
  j_marble: 'Uncommon',
  j_loyalty_card: 'Uncommon',
  j_8_ball: 'Common',
  j_misprint: 'Common',
  j_dusk: 'Uncommon',
  j_raised_fist: 'Common',
  j_chaos: 'Common',
  j_fibonacci: 'Uncommon',
  j_steel_joker: 'Uncommon',
  j_scary_face: 'Common',
  j_abstract: 'Common',
  j_delayed_grat: 'Common',
  j_hack: 'Uncommon',
  j_pareidolia: 'Uncommon',
  j_gros_michel: 'Common',
  j_even_steven: 'Common',
  j_odd_todd: 'Common',
  j_scholar: 'Common',
  j_business: 'Common',
  j_supernova: 'Common',
  j_ride_the_bus: 'Common',
  j_space: 'Uncommon',
  j_egg: 'Common',
  j_burglar: 'Uncommon',
  j_blackboard: 'Uncommon',
  j_runner: 'Common',
  j_ice_cream: 'Common',
  j_dna: 'Rare',
  j_splash: 'Common',
  j_blue_joker: 'Common',
  j_sixth_sense: 'Uncommon',
  j_constellation: 'Uncommon',
  j_hiker: 'Uncommon',
  j_faceless: 'Common',
  j_green_joker: 'Common',
  j_superposition: 'Common',
  j_todo_list: 'Common',
  j_cavendish: 'Common',
  j_card_sharp: 'Uncommon',
  j_red_card: 'Common',
  j_madness: 'Uncommon',
  j_square: 'Common',
  j_seance: 'Uncommon',
  j_riff_raff: 'Common',
  j_vampire: 'Uncommon',
  j_shortcut: 'Uncommon',
  j_hologram: 'Uncommon',
  j_vagabond: 'Rare',
  j_baron: 'Rare',
  j_cloud_9: 'Uncommon',
  j_rocket: 'Uncommon',
  j_obelisk: 'Rare',
  j_midas_mask: 'Uncommon',
  j_luchador: 'Uncommon',
  j_photograph: 'Common',
  j_gift: 'Uncommon',
  j_turtle_bean: 'Uncommon',
  j_erosion: 'Uncommon',
  j_reserved_parking: 'Common',
  j_mail: 'Common',
  j_to_the_moon: 'Uncommon',
  j_hallucination: 'Common',
  j_fortune_teller: 'Common',
  j_juggler: 'Common',
  j_drunkard: 'Common',
  j_stone: 'Uncommon',
  j_golden: 'Common',
  j_lucky_cat: 'Uncommon',
  j_baseball: 'Rare',
  j_bull: 'Uncommon',
  j_diet_cola: 'Uncommon',
  j_trading: 'Uncommon',
  j_flash: 'Uncommon',
  j_popcorn: 'Common',
  j_trousers: 'Uncommon',
  j_ancient: 'Rare',
  j_ramen: 'Uncommon',
  j_walkie_talkie: 'Common',
  j_selzer: 'Uncommon',
  j_castle: 'Uncommon',
  j_smiley: 'Common',
  j_campfire: 'Rare',
  j_ticket: 'Common',
  j_mr_bones: 'Uncommon',
  j_acrobat: 'Uncommon',
  j_sock_and_buskin: 'Uncommon',
  j_swashbuckler: 'Common',
  j_troubadour: 'Uncommon',
  j_certificate: 'Uncommon',
  j_smeared: 'Uncommon',
  j_throwback: 'Uncommon',
  j_hanging_chad: 'Common',
  j_rough_gem: 'Uncommon',
  j_bloodstone: 'Uncommon',
  j_arrowhead: 'Uncommon',
  j_onyx_agate: 'Uncommon',
  j_glass: 'Uncommon',
  j_ring_master: 'Uncommon',
  j_flower_pot: 'Uncommon',
  j_blueprint: 'Rare',
  j_wee: 'Rare',
  j_merry_andy: 'Uncommon',
  j_oops: 'Uncommon',
  j_idol: 'Uncommon',
  j_seeing_double: 'Uncommon',
  j_matador: 'Uncommon',
  j_hit_the_road: 'Rare',
  j_duo: 'Rare',
  j_trio: 'Rare',
  j_family: 'Rare',
  j_order: 'Rare',
  j_tribe: 'Rare',
  j_stuntman: 'Rare',
  j_invisible: 'Rare',
  j_brainstorm: 'Rare',
  j_satellite: 'Uncommon',
  j_shoot_the_moon: 'Common',
  j_drivers_license: 'Rare',
  j_cartomancer: 'Uncommon',
  j_astronomer: 'Uncommon',
  j_burnt: 'Rare',
  j_bootstraps: 'Uncommon',
  j_caino: 'Legendary',
  j_triboulet: 'Legendary',
  j_yorick: 'Legendary',
  j_chicot: 'Legendary',
  j_perkeo: 'Legendary',
}

export const deckNames: Record<string, string> = {
  b_red: 'Red Deck',
  b_blue: 'Blue Deck',
  b_yellow: 'Yellow Deck',
  b_green: 'Green Deck',
  b_black: 'Black Deck',
  b_magic: 'Magic Deck',
  b_nebula: 'Nebula Deck',
  b_ghost: 'Ghost Deck',
  b_abandoned: 'Abandoned Deck',
  b_checkered: 'Checkered Deck',
  b_zodiac: 'Zodiac Deck',
  b_painted: 'Painted Deck',
  b_anaglyph: 'Anaglpyh Deck',
  b_plasma: 'Plasma Deck',
  b_erratic: 'Erratic Deck',
}

export const deckSprites: Record<string, string> = {
  b_red: '0 0',
  b_blue: '0 -200%',
  b_yellow: '-100% -200%',
  b_green: '-200% -200%',
  b_black: '-300% -200%',
  b_magic: '0 -300%',
  b_nebula: '-300% 0',
  b_ghost: '-600% -200%',
  b_abandoned: '-300% -300%',
  b_checkered: '-100% -300%',
  b_zodiac: '-300% -400%',
  b_painted: '-400% -300%',
  b_anaglyph: '-200% -400%',
  b_plasma: '-400% -200%',
  b_erratic: '-200% -300%',
}

export const consumableNames: Record<string, string> = {
  c_fool: 'The Fool',
  c_magician: 'The Magician',
  c_high_priestess: 'The High Priestess',
  c_empress: 'The Empress',
  c_emperor: 'The Emperor',
  c_heirophant: 'The Hierophant',
  c_lovers: 'The Lovers',
  c_chariot: 'The Chariot',
  c_justice: 'Justice',
  c_hermit: 'The Hermit',
  c_wheel_of_fortune: 'The Wheel of Fortune',
  c_strength: 'Strength',
  c_hanged_man: 'The Hanged Man',
  c_death: 'Death',
  c_temperance: 'Temperance',
  c_devil: 'The Devil',
  c_tower: 'The Tower',
  c_star: 'The Star',
  c_moon: 'The Moon',
  c_sun: 'The Sun',
  c_judgement: 'Judgement',
  c_world: 'The World',

  c_mercury: 'Mercury',
  c_venus: 'Venus',
  c_earth: 'Earth',
  c_mars: 'Mars',
  c_jupiter: 'Jupiter',
  c_saturn: 'Saturn',
  c_uranus: 'Uranus',
  c_neptune: 'Neptune',
  c_pluto: 'Pluto',
  c_planet_x: 'Planet X',
  c_ceres: 'Ceres',
  c_eris: 'Eris',

  c_familiar: 'Familiar',
  c_grim: 'Grim',
  c_incantation: 'Incantation',
  c_talisman: 'Talisman',
  c_aura: 'Aura',
  c_wraith: 'Wraith',
  c_sigil: 'Sigil',
  c_ouija: 'Ouija',
  c_ectoplasm: 'Ectoplasm',
  c_immolate: 'Immolate',
  c_ankh: 'Ankh',
  c_deja_vu: 'Deja Vu',
  c_hex: 'Hex',
  c_trance: 'Trance',
  c_medium: 'Medium',
  c_cryptid: 'Cryptid',
  c_soul: 'The Soul',
  c_black_hole: 'Black Hole',
}

export const consumableSprites: Record<string, string> = {
  c_fool: '0 0',
  c_magician: '-100% 0',
  c_high_priestess: '-200% 0',
  c_empress: '-300% 0',
  c_emperor: '-400% 0',
  c_heirophant: '-500% 0',
  c_lovers: '-600% 0',
  c_chariot: '-700% 0',
  c_justice: '-800% 0',
  c_hermit: '-900% 0',
  c_wheel_of_fortune: '0 -100%',
  c_strength: '-100% -100%',
  c_hanged_man: '-200% -100%',
  c_death: '-300% -100%',
  c_temperance: '-400% -100%',
  c_devil: '-500% -100%',
  c_tower: '-600% -100%',
  c_star: '-700% -100%',
  c_moon: '-800% -100%',
  c_sun: '-900% -100%',
  c_judgement: '0 -200%',
  c_world: '-100% -200%',

  c_mercury: '0 -300%',
  c_venus: '-100% -300%',
  c_earth: '-200% -300%',
  c_mars: '-300% -300%',
  c_jupiter: '-400% -300%',
  c_saturn: '-500% -300%',
  c_uranus: '-600% -300%',
  c_neptune: '-700% -300%',
  c_pluto: '-800% -300%',
  c_planet_x: '-900% -200%',
  c_ceres: '-800% -200%',
  c_eris: '-300% -200%',

  c_familiar: '0 -400%',
  c_grim: '-100% -400%',
  c_incantation: '-200% -400%',
  c_talisman: '-300% -400%',
  c_aura: '-400% -400%',
  c_wraith: '-500% -400%',
  c_sigil: '-600% -400%',
  c_ouija: '-700% -400%',
  c_ectoplasm: '-800% -400%',
  c_immolate: '-900% -400%',
  c_ankh: '0 -500%',
  c_deja_vu: '-100% -500%',
  c_hex: '-200% -500%',
  c_trance: '-300% -500%',
  c_medium: '-400% -500%',
  c_cryptid: '-500% -500%',
  c_soul: '-200% -200%',
  c_black_hole: '-900% -300%',
}

export const voucherNames: Record<string, string> = {
  v_overstock_norm: 'Overstock',
  v_overstock_plus: 'Overstock Plus',
  v_clearance_sale: 'Clearance Sale',
  v_liquidation: 'Liquidation',
  v_hone: 'Hone',
  v_glow_up: 'Glow Up',
  v_reroll_surplus: 'Reroll Surplus',
  v_reroll_glut: 'Reroll Glut',
  v_crystal_ball: 'Crystal Ball',
  v_omen_globe: 'Omen Globe',
  v_telescope: 'Telescope',
  v_observatory: 'Observatory',
  v_grabber: 'Grabber',
  v_nacho_tong: 'Nacho Tong',
  v_wasteful: 'Wasteful',
  v_recyclomancy: 'Recyclomancy',
  v_tarot_merchant: 'Tarot Merchant',
  v_tarot_tycoon: 'Tarot Tycoon',
  v_planet_merchant: 'Planet Merchant',
  v_planet_tycoon: 'Planet Tycoon',
  v_seed_money: 'Seed Money',
  v_money_tree: 'Money Tree',
  v_blank: 'Blank',
  v_antimatter: 'Antimatter',
  v_magic_trick: 'Magic Trick',
  v_illusion: 'Illusion',
  v_hieroglyph: 'Hieroglpyh',
  v_petroglyph: 'Petroglpyh',
  v_directors_cut: "Director's Cut",
  v_retcon: 'Retcon',
  v_paint_brush: 'Paint Brush',
  v_palette: 'Palette',
}

export const voucherSprites: Record<string, string> = {
  v_overstock_norm: '0 0',
  v_overstock_plus: '0 -100%',
  v_clearance_sale: '-300% 0',
  v_liquidation: '-300% -100%',
  v_hone: '-400% 0',
  v_glow_up: '-400% -100%',
  v_reroll_surplus: '0 -200%',
  v_reroll_glut: '0 -300%',
  v_crystal_ball: '-200% -200%',
  v_omen_globe: '-200% -300%',
  v_telescope: '-300% -200%',
  v_observatory: '-300% -300%',
  v_grabber: '-500% 0',
  v_nacho_tong: '-500% -100%',
  v_wasteful: '-600% 0',
  v_recyclomancy: '-600% -100%',
  v_tarot_merchant: '-100% 0',
  v_tarot_tycoon: '-100% -100%',
  v_planet_merchant: '-200% 0',
  v_planet_tycoon: '-200% -100%',
  v_seed_money: '-100% -200%',
  v_money_tree: '-100% -300%',
  v_blank: '-700% 0',
  v_antimatter: '-700% -100%',
  v_magic_trick: '-400% -200%',
  v_illusion: '-400% -300%',
  v_hieroglyph: '-500% -200%',
  v_petroglyph: '-500% -300%',
  v_directors_cut: '-600% -200%',
  v_retcon: '-600% -300%',
  v_paint_brush: '-700% -200%',
  v_palette: '-700% -300%',
}
